project:
  type: website
  output-dir: docs

website:
  title: "OuMark"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - text: TSDFGS (R package)
            href: https://www.oumark.net/TSDFGS/
      - text: Teaching
        menu:
          - text: GWAS (3MR103)
            href: https://www.oumark.net/3MR103

format:
  html:
    theme: 
      light: simplex
      dark: darkly
    css: styles.css
    toc: true



