project:
  type: website
  output-dir: docs

website:
  title: "OuMark"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - text: TSDFGS (R package)
            href: https://www.oumark.net/TSDFGS/
          - text: GENO2R (R package)
            href: https://www.oumark.net/geno2r/
          - text: Poster (ISAG 2023)
            href: https://www.oumark.net/download/poster_isag2023.pdf
      - text: Teaching
        menu:
          - text: GWAS (3MR103)
            href: https://www.oumark.net/3MR103
      - text: Resumé
        file: resume/resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



